[package]
name = "crux_core"
description = "Cross-platform app development in Rust"
version = "0.12.2"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["dep:serde-generate", "dep:serde-reflection"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow.workspace = true
bincode = "1.3.3"
crossbeam-channel = "0.5.14"
crux_macros = { version = "0.4.5", path = "../crux_macros" }
erased-serde = "0.4"
futures = "0.3.31"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.140"
slab = "0.4.9"
thiserror = "2.0.12"

# we can't update serde_generate and serde_reflection yet,
# as it appears that our undiscovered types aren't registering properly.
# So I've left them 0.26.0 and 0.4.0 respectively.
serde-generate = { version = "0.26.0", optional = true }
serde-reflection = { version = "0.4.0", optional = true }
either = "1.14.0"
async-std = {version = "1.13.0", features = ["unstable"] }
tracing = "0.1.41"
wasm-bindgen-futures = "0.4.50"
streamunordered = "0.5.4"

[dev-dependencies]
assert_fs = "1.1.2"
assert_matches = "1.5"
async-channel = "2.3"
crux_http = { path = "../crux_http" }
crux_time = { path = "../crux_time" }
crux_kv = { path = "../crux_kv" }
doctest_support = { path = "../doctest_support" }
serde = { version = "1.0.218", features = ["derive"] }
static_assertions = "1.1"
rand = "0.9"
url = "2.5.4"
uuid = { version = "1.15.1", features = ["v4", "serde"] }
