[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
serde = { workspace = true, features = ["derive"] }
lazy_static = "1.5.0"
uniffi = "=0.28.3"
wasm-bindgen = "0.2.100"
async-std = "1.13.0"
async-stream = "0.3.6"
futures = "0.3.31"
futures-util = "0.3.31"
wasm-bindgen-futures = "0.4.50"
wasm-timer = "0.2.5"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "=0.28.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "=0.28.3", features = ["build"] }
